basePath: /
definitions:
  models.Attendance:
    properties:
      id:
        type: integer
      student_id:
        type: integer
      subject_id:
        type: integer
      visit_day:
        type: string
      visited:
        type: boolean
    type: object
  models.AuthenticationReq:
    properties:
      email:
        type: string
      password:
        type: string
      role:
        type: string
    type: object
  models.Grade:
    properties:
      credits:
        type: integer
      grade:
        type: number
      id:
        type: integer
      student_id:
        type: integer
      subject_id:
        type: integer
    type: object
  models.GroupReq:
    properties:
      groupname:
        type: string
    type: object
  models.GroupSchedule:
    properties:
      end_time:
        type: string
      group_id:
        type: integer
      id:
        type: integer
      start_time:
        type: string
      subject:
        type: string
    type: object
  models.Instructor:
    properties:
      birth_date:
        type: string
      gender:
        type: string
      id:
        type: integer
      name:
        type: string
      title_name:
        type: integer
    type: object
  models.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.Student:
    properties:
      birth_date:
        type: string
      gender:
        type: string
      group_id:
        type: integer
      group_name:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  models.StudentReq:
    properties:
      birth_date:
        type: string
      gender:
        type: string
      group_id:
        type: integer
      name:
        type: string
    type: object
  models.User:
    properties:
      email:
        type: string
      id:
        type: integer
      role:
        type: string
    type: object
host: university-management-app-oojg.onrender.com
info:
  contact: {}
  description: Swagger API
  title: Deployment of university app and swagger just for info
paths:
  /all_class_schedule:
    get:
      description: Get all groups' schedules
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.GroupSchedule'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all groups' schedules
      tags:
      - schedule
  /api/auth/login:
    post:
      description: Handler for Login
      parameters:
      - description: Account Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Login user
      tags:
      - auth
  /api/auth/register:
    post:
      description: Handler for Registration
      parameters:
      - description: Account Credentials
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.AuthenticationReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
      summary: Register user
      tags:
      - auth
  /api/users/me:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
      security:
      - BearerAuth: []
      summary: Get current user info
      tags:
      - users
  /attendance/subject:
    post:
      consumes:
      - application/json
      description: Insert attendance info
      parameters:
      - description: Attendance Info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.Attendance'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Insert attendance info
      tags:
      - attendace
  /attendanceByStudentId/{id}:
    get:
      description: Get student's attendance info by ID
      parameters:
      - description: Student Id
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Attendance'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get student's attendance info
      tags:
      - attendace
  /attendanceBySubjectId/{id}:
    get:
      description: Get attendance info of the subject by ID
      parameters:
      - description: Subject Id
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Attendance'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get attendance info of the subject
      tags:
      - attendace
  /group/create:
    post:
      consumes:
      - application/json
      description: Insert Group Info
      parameters:
      - description: Group Info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.GroupReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Insert Group Info
      tags:
      - group
  /instructor/{id}:
    get:
      description: Get instructor info by ID
      parameters:
      - description: Instructor Id
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Instructor'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get instructor info
      tags:
      - instructor
  /schedule/group/{id}:
    get:
      description: Get group's schedule by ID
      parameters:
      - description: Group Id
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.GroupSchedule'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get group's schedule
      tags:
      - schedule
  /student/{id}:
    get:
      description: Get student info by ID
      parameters:
      - description: Student Id
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Student'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get student info
      tags:
      - student
  /student/create:
    post:
      consumes:
      - application/json
      description: Insert Student Info
      parameters:
      - description: Student Info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/models.StudentReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Insert Student Info
      tags:
      - student
  /student/grades/{id}:
    get:
      description: Get student's grades by ID
      parameters:
      - description: Student Id
        in: path
        name: input
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Grade'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get student's grades info
      tags:
      - grades
schemes:
- https
swagger: "2.0"
